// Generated by `npx drizzle-kit pull` after 0001_init.sql is applied to the
// live database — SQL migrations in db/migrations/ are the source of truth,
// this file is a typed mirror of them. Do not hand-edit; re-run the pull.
export {};
